### PR TITLE
Add an information telling that a trip has no shape

### LINKED ISSUE #122: Additional warning: no shapes for trips
https://github.com/etalab/transport-site/issues/2331

### PR DESCRIPTION
**Pull request by antoine-de**
Closes #122

It's only an information as it's completly valid

### CODE REVIEW

**Review by Tristramg — APPROVED** [review]

**Comment by antoine-de** [comment]
ping @AntoineAugusti , do you want to review this or can I merge it?

**Comment by AntoineAugusti** [comment]
Wondering if this is the best approach. If we have a large number of trips, we will emit a very large payload for each trip. Would it be best to emit metadata, with a ratio of trips without shapes?

**Comment by antoine-de** [comment]
yes, you're right it's not a bad idea a global stat will be enough, I'll change this :+1:

**Comment by antoine-de** [comment]
Add a `trips_with_shape_count` metadata
    
Since it's quite a common thing not ot have a shape for trips Instead of a noisy issue, add a global stat.
    
Count the number of trips with a shape (not wihtout) since it's more consistent with the other metadata.

**Comment by antoine-de** [comment]
ping @AntoineAugusti does that seems ok for you?

**Comment by AntoineAugusti** [comment]
LGTM, thanks!

**Pull request merged**
