### PR TITLE
bump gtfs-structures version to 0.24.0

### LINKED ISSUE #1660: Rapport de validation GTFS non généré
Pour le dataset suivant : https://transport.data.gouv.fr/datasets/reseau-transisere-donnees-theoriques/

La validation indique une erreur irrécupérable. Pourtant le rapport de validation est inexistant.

Après avoir creusé, il semble que notre validateur utilise la crate Rust gtfs-structure, qui n'arrive pas à charger le GTFS de la ressource. J'ai ouvert un ticket dans le repo correspondant : https://github.com/rust-transit/gtfs-structure/issues/78

### PR DESCRIPTION
**Pull request by fchabouis**
closes https://github.com/etalab/transport-site/issues/1660

There was a probleml with `gtfs_structures::RawGtfs::from_url_async`, making it impossible to fetch some remote resources.

See https://github.com/rust-transit/gtfs-structure/issues/78 for more details

### CODE REVIEW

**Comment by fchabouis** [comment]
@antoine-de or @Tristramg, my cargo.lock now contains dependencies versions. Versions were not specified before. Any idea why ? Thanks !

**Comment by fchabouis** [comment]
Also I had to add default values to a feed for a test to pass, I'm wondering why I had to do this, I haven't touched the code except for the version bump.

**Comment by Tristramg** [comment]
concerning the extra fields, it is because they were added by an external
contribution
https://github.com/rust-transit/gtfs-structure/commit/8ac9ce9b3688a3db24d6394c4b317f387f157720
We probably should implement Default to handle those extra fields without
too much pain (but a default value for an Id does not make sense, so not as
trivial)

For the explicit version, my guess (but not completly sure) is that
gtfs-structure bumped to bytes 1 (
https://github.com/rust-transit/gtfs-structure/commit/d677624f4e3034701fbae4572ad2b3787769f959)
while an other crate depends on bytes 0.5. Because there are two versions
required, they must be defined explicitely

**Review by Tristramg — APPROVED** [review]

**Comment by antoine-de** [comment]
yep your actix version still uses bytes 0.5 so 2 versions needs to exist in your dependency tree (but that's ok)

you can update actix to `"4.0.0-beta.6"` to have `bytes=1` (and tokio 1), but I'm not sure it's worth it.

I tried it a a branch, I can open a PR with it if you want since everything is ok with the bump (you can see it [here](https://github.com/etalab/transport-validator/compare/update_all_versions?expand=1) I also tided up a dependency). I can also push in you branch if you think it's easier.

**Comment by fchabouis** [comment]
Thank you for the feedback guys. I will merge it now, but do not hesitate to open another PR for the proposed changes @antoine-de  we will gladly accept it.

**Pull request merged**
