### PR TITLE
Use subfolder rule

### PR DESCRIPTION
**Pull request by antoine-de**
Sorry, forgot this step...

### CODE REVIEW

**Review by thbar — APPROVED** [review]
Sounds reasonable :-) Thanks for detecting it!

**Comment by AntoineAugusti** [comment]
Related to #176

**Comment by AntoineAugusti** [comment]
@thbar 🕵️ https://mattermost.incubateur.net/betagouv/pl/z6ykpwa43tggdesfwaqkgy8ssy

**Comment by thbar** [comment]
Merci @AntoineAugusti !

**Pull request merged**
