### PR TITLE
Bump gtfs structure version

### PR DESCRIPTION
**Pull request by antoine-de**
Bump GTFS structure version, gaining all the memory optimization that were done in the library

Reading a IDFM dataset

From the main branch, the peak memory was 2 221 228 

From this branch, the peak memory was 1 828 052

Also bump geo version, since there is a new one (and the old one was breaking the compilation with a weird max recursion bug).

### CODE REVIEW

**Review by Tristramg — APPROVED** [review]

**Comment by thbar** [comment]
Nice! Thank you for the improvement!

**Review by Tristramg — APPROVED** [review]

**Comment by antoine-de** [comment]
@AntoineAugusti @thbar 

are you ok if we merge both this PR and #174 on monday? I'll try to also do a whole dependency update and https://github.com/etalab/transport-validator/issues/160 next week

**Comment by AntoineAugusti** [comment]
@antoine-de Can you wait to merge #174 at least a week? I need to review if we need to update the UI/some translations on transport.data.gouv.fr to deal with this new error.

**Comment by antoine-de** [comment]
yes sure, it can wait :+1:

**Comment by antoine-de** [comment]
linked to https://github.com/etalab/transport-validator/issues/172 (but I don't know if we can close it, as we'll need to see if it's enough)

**Pull request merged**
