### PR TITLE
Limit to 1000 results per kind of issue

### PR DESCRIPTION
**Pull request by Tristramg**

### CODE REVIEW

**Review by l-vincent-l — COMMENTED** [review]
Can you think of something to be able to tell in the API about the real number of errors?

**Comment by Tristramg** [comment]
We could do that, but it would change the api as we need to nest the data an extra-step.

Or we could put in the metadata, but that seems odd.

Do you have a preference ? (doing nothing could be a possibility :p)

**Comment by l-vincent-l** [comment]
I think, it may be done in metadata, I can't think of a better solution right now

**Comment by Tristramg** [comment]
It’s now in the metadata.

And the number is controllable in the api or in the cli (1000 by default)

**Review by antoine-de — COMMENTED** [review]
fine for me, but for the lack of a test 😉

**Review by antoine-de — APPROVED** [review]

**Pull request merged**
